apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: networktools
  namespace: networktools
spec:
  to:
    kind: Service
    name: networktools
  port:
    targetPort: dummy
  tls:
    termination: edge

